INSERT INTO employees
  (title, salary, department_id)
VALUES
  ('James', 'Fraser', '333'),
  ('Jack', 'London', '212'),
  ('Robert', 'Bruce', '212'),
  ('Peter', 'Greenaway', '703'),
  ('Derek', 'Jarman', '703'),
  ('Paolo', 'Pasolini', '333'),
  ('Heathcote', 'Williams', '333'),
  ('Sandy', 'Powell', '333'),
  ('Emil', 'Zola', '212'),
  ('Sissy', 'Coalpits', '703'),
  ('Antoinette', 'Capet', '703'),
  ('Samuel', 'Delany', '101'),
  ('Tony', 'Duvert', '411'),
  ('Dennis', 'Cooper', '411'),
  ('Monica', 'Bellucci', '333'),
  ('Samuel', 'Johnson', '212'),
  ('John', 'Dryden', '703'),
  ('Alexander', 'Pope', '101'),
  ('Lionel', 'Johnson', '212'),
  ('Aubrey', 'Beardsley', '212'),
  ('Tulse', 'Luper', '333'),
  ('William', 'Morris', '333'),
  ('George', 'Shaw', '703'),
  ('Arnold', 'Bennett', '703'),
  ('Algernon', 'Blackwood', '212'),
  ('Rhoda', 'Broughton', '333'),
  ('Hart', 'Crane', '333'),
  ('Vitorio', 'DeSica', '101'),
  ('Wilkie', 'Collins', '101'),
  ('Elizabeth', 'Gaskell', '101'),
  ('George', 'Sand', '101'),
  ('Vernon', 'Lee', '411'),
  ('Arthur', 'Machen', '411'),
  ('Frederick', 'Marryat', '411'),
  ('Harriet', 'Martineau', '411'),
  ('George', 'Meredith', '411'),
  ('Margaret', 'Oliphant', '411'),
  ('Anthony', 'Trollope', '411'),
  ('Charlotte', 'Yonge', '411'),
  ('Horace', 'Walpole', '411'),
  ('Matthew', 'Lewis', '333'),
  ('William', 'Bedford', '703'),
  ('Anne', 'Radcliffe', '212'),
  ('Charles', 'Brown', '212'),
  ('Eliza', 'Parsons', '333'),
  ('Susan', 'Hill', '703'),
  ('Sydney', 'Owenson', '703'),
  ('Hubert', 'Crackanthorpe', '212'),
  ('William', 'Carleton', '212'),
  ('Gerald', 'Griffin', '333');

INSERT INTO department
  (name)
VALUES
  ('Human Resources'),
  ('Engineering'),
  ('Marketing'),
  ('R & D'),
  ('Sales');

INSERT INTO employee
  (first_name, last_name, role_id, manager_id)
VALUES
  ('Ronald', 'Firbank', 1, 1),
  ('Virginia', 'Woolf', 1, 1),
  ('Piers', 'Gaveston', 1, 0),
  ('Charles', 'LeRoi', 2, 1),
  ('Katherine', 'Mansfield', 2, 1),
  ('Dora', 'Carrington', 3, 0),
  ('Edward', 'Bellamy', 3, 0),
  ('Montague', 'Summers', 3, 1),
  ('Octavia', 'Butler', 3, 1),
  ('Unica', 'Zurn', NULL, 1);
   ('James', 'Fraser', 3, 2),
  ('Jack', 'London', 3, 1),
  ('Robert', 'Bruce', 2, 1),
  ('Peter', 'Greenaway', 1, 0),
  ('Derek', 'Jarman', 1, 0),
  ('Paolo', 'Pasolini', 2, 1),
  ('Heathcote', 'Williams', 2, 1),
  ('Sandy', 'Powell', 2, 1),
  ('Emil', 'Zola', 4, 1),
  ('Sissy', 'Coalpits', 5, 0),
  ('Antoinette', 'Capet', 5, 2),
  ('Samuel', 'Delany', 3, 1),
  ('Tony', 'Duvert', 1, 3),
  ('Dennis', 'Cooper', 1, 2),
  ('Monica', 'Bellucci', 2, 1),
  ('Samuel', 'Johnson', 4, 1),
  ('John', 'Dryden', 5, 1),
  ('Alexander', 'Pope', 3, 1),
  ('Lionel', 'Johnson', 4, 1),
  ('Aubrey', 'Beardsley', 4, 1),
  ('Tulse', 'Luper', 2, 1),
  ('William', 'Morris', 2, 1),
  ('George', 'Shaw', 5, 1),
  ('Arnold', 'Bennett', 2, 1),
  ('Algernon', 'Blackwood', 2, 1),
  ('Rhoda', 'Broughton', 3, 3),
  ('Hart', 'Crane', 3, 3),
  ('Vitorio', 'DeSica', 3, 1),
  ('Wilkie', 'Collins', 3, 1),
  ('Elizabeth', 'Gaskell', 1, 0),
  ('George', 'Sand', 1, 0),
  ('Vernon', 'Lee', 4, 1),
  ('Arthur', 'Machen', 4, 2),
  ('Frederick', 'Marryat', 4, 3),
  ('Harriet', 'Martineau', 4, 1),
  ('George', 'Meredith', 4, 1),
  ('Margaret', 'Oliphant', 4, 3),
  ('Anthony', 'Trollope', 4, 2),
  ('Charlotte', 'Yonge', 4, 1),
  ('Horace', 'Walpole', 4, 0),
  ('Matthew', 'Lewis', 3, 1),
  ('William', 'Bedford', 2, 1),
  ('Anne', 'Radcliffe', 2, 1),
  ('Charles', 'Brown', 2, 1),
  ('Eliza', 'Parsons', 3, 0),
  ('Susan', 'Hill', 2, 0),
  ('Sydney', 'Owenson', 2, 2),
  ('Hubert', 'Crackanthorpe', 2, 0),
  ('William', 'Carleton', 2, 2),
  ('Gerald', 'Griffin', 3, 1);
  